### ISSUE TITLE
about Uni-Fold bibtex

### ISSUE THREAD

**Issue by GuoxiaWang** [dptech-corp/Uni-Fold-jax#22]
Can you post a bibtex to cite?

**Comment by ZiyaoLi** [comment]
Thank you for your interest in Uni-Fold. Currently we have not published papers about Uni-Fold, so perhaps you may acknowledge Uni-Fold by citing the repo's URL.

**Comment by ZiyaoLi** [comment]
We have now added the citation in Readme. Refer to our preprint for more details :)
