### ISSUE TITLE
Looking forward to your pytorch code.

### ISSUE THREAD

**Issue by CerrieJ** [dptech-corp/Uni-Fold-jax#23]
I'm looking forward to your pytorch code ♥, do you have a release plan?

**Comment by ZiyaoLi** [comment]
We are working on the final experiments and examination of Uni-Fold PyTorch (v1.1.0) as well as Uni-Fold Multimer (v2.0.0). The code is likely to come out in coming two months.

**Comment by guolinke** [comment]
Please check https://github.com/dptech-corp/Uni-Fold
